/**
 * Photography Dataset: 123 Photos across 8 Series
 * Brian Lam Photography Archive
 */
window.photosData = [
  {
    "id": 1,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #01",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/1.jpg",
    "thumb": "assets/photography/nyc2021/1.jpg",
    "featured": true
  },
  {
    "id": 2,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #02",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/2.jpg",
    "thumb": "assets/photography/nyc2021/2.jpg",
    "featured": false
  },
  {
    "id": 3,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #03",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/3.jpg",
    "thumb": "assets/photography/nyc2021/3.jpg",
    "featured": false
  },
  {
    "id": 4,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #04",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/4.jpg",
    "thumb": "assets/photography/nyc2021/4.jpg",
    "featured": false
  },
  {
    "id": 5,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #05",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/5.jpg",
    "thumb": "assets/photography/nyc2021/5.jpg",
    "featured": false
  },
  {
    "id": 6,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #06",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/6.jpg",
    "thumb": "assets/photography/nyc2021/6.jpg",
    "featured": false
  },
  {
    "id": 7,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #07",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/7.jpg",
    "thumb": "assets/photography/nyc2021/7.jpg",
    "featured": false
  },
  {
    "id": 8,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #08",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/8.jpg",
    "thumb": "assets/photography/nyc2021/8.jpg",
    "featured": false
  },
  {
    "id": 9,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #09",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/9.jpg",
    "thumb": "assets/photography/nyc2021/9.jpg",
    "featured": false
  },
  {
    "id": 10,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #10",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/10.jpg",
    "thumb": "assets/photography/nyc2021/10.jpg",
    "featured": false
  },
  {
    "id": 11,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #11",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/11.jpg",
    "thumb": "assets/photography/nyc2021/11.jpg",
    "featured": false
  },
  {
    "id": 12,
    "series": "nyc2021",
    "seriesTitle": "New York City (2021)",
    "category": "nyc",
    "title": "New York City \u00b7 #12",
    "location": "New York, NY",
    "year": "2021",
    "src": "assets/photography/nyc2021/12.jpg",
    "thumb": "assets/photography/nyc2021/12.jpg",
    "featured": false
  },
  {
    "id": 13,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #01",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/01-large.png",
    "thumb": "assets/photography/nyc2020/01.png",
    "featured": false
  },
  {
    "id": 14,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #02",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/02-large.png",
    "thumb": "assets/photography/nyc2020/02.png",
    "featured": false
  },
  {
    "id": 15,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #03",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/03-large.png",
    "thumb": "assets/photography/nyc2020/03.png",
    "featured": false
  },
  {
    "id": 16,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #04",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/04-large.png",
    "thumb": "assets/photography/nyc2020/04.png",
    "featured": false
  },
  {
    "id": 17,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #05",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/05.jpg",
    "thumb": "assets/photography/nyc2020/05.jpg",
    "featured": false
  },
  {
    "id": 18,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #06",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/06.jpg",
    "thumb": "assets/photography/nyc2020/06.jpg",
    "featured": false
  },
  {
    "id": 19,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #07",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/07.jpg",
    "thumb": "assets/photography/nyc2020/07.jpg",
    "featured": false
  },
  {
    "id": 20,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #08",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/08.jpg",
    "thumb": "assets/photography/nyc2020/08.jpg",
    "featured": false
  },
  {
    "id": 21,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #09",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/09.png",
    "thumb": "assets/photography/nyc2020/09.png",
    "featured": false
  },
  {
    "id": 22,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #10",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/10.jpg",
    "thumb": "assets/photography/nyc2020/10.jpg",
    "featured": false
  },
  {
    "id": 23,
    "series": "nyc2020",
    "seriesTitle": "New York City (2020)",
    "category": "nyc",
    "title": "New York City \u00b7 #11",
    "location": "New York, NY",
    "year": "2020",
    "src": "assets/photography/nyc2020/11.jpg",
    "thumb": "assets/photography/nyc2020/11.jpg",
    "featured": false
  },
  {
    "id": 24,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #01",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/1-large.png",
    "thumb": "assets/photography/nyc2019/1.png",
    "featured": false
  },
  {
    "id": 25,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #02",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/2-large.png",
    "thumb": "assets/photography/nyc2019/2.png",
    "featured": false
  },
  {
    "id": 26,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #03",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/3-large.png",
    "thumb": "assets/photography/nyc2019/3.png",
    "featured": false
  },
  {
    "id": 27,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #04",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/4-large.png",
    "thumb": "assets/photography/nyc2019/4.png",
    "featured": false
  },
  {
    "id": 28,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #05",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/5-large.png",
    "thumb": "assets/photography/nyc2019/5.png",
    "featured": false
  },
  {
    "id": 29,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #06",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/6-large.png",
    "thumb": "assets/photography/nyc2019/6.png",
    "featured": false
  },
  {
    "id": 30,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #07",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/7-large.png",
    "thumb": "assets/photography/nyc2019/7.png",
    "featured": false
  },
  {
    "id": 31,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #08",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/8-large.png",
    "thumb": "assets/photography/nyc2019/8.png",
    "featured": false
  },
  {
    "id": 32,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #09",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/9-large.png",
    "thumb": "assets/photography/nyc2019/9.png",
    "featured": false
  },
  {
    "id": 33,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #10",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/10-large.png",
    "thumb": "assets/photography/nyc2019/10.png",
    "featured": false
  },
  {
    "id": 34,
    "series": "nyc2019",
    "seriesTitle": "New York City (2019)",
    "category": "nyc",
    "title": "New York City \u00b7 #11",
    "location": "New York, NY",
    "year": "2019",
    "src": "assets/photography/nyc2019/11-large.png",
    "thumb": "assets/photography/nyc2019/11.png",
    "featured": false
  },
  {
    "id": 35,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #01",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/01.jpg",
    "thumb": "assets/photography/tokyo2017/01.jpg",
    "featured": true
  },
  {
    "id": 36,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #02",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/02.jpg",
    "thumb": "assets/photography/tokyo2017/02.jpg",
    "featured": false
  },
  {
    "id": 37,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #03",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/03.jpg",
    "thumb": "assets/photography/tokyo2017/03.jpg",
    "featured": false
  },
  {
    "id": 38,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #04",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/04.jpg",
    "thumb": "assets/photography/tokyo2017/04.jpg",
    "featured": false
  },
  {
    "id": 39,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #05",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/05.jpg",
    "thumb": "assets/photography/tokyo2017/05.jpg",
    "featured": false
  },
  {
    "id": 40,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #06",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/06.jpg",
    "thumb": "assets/photography/tokyo2017/06.jpg",
    "featured": true
  },
  {
    "id": 41,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #07",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/07.jpg",
    "thumb": "assets/photography/tokyo2017/07.jpg",
    "featured": false
  },
  {
    "id": 42,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #08",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/08.jpg",
    "thumb": "assets/photography/tokyo2017/08.jpg",
    "featured": false
  },
  {
    "id": 43,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #09",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/09.jpg",
    "thumb": "assets/photography/tokyo2017/09.jpg",
    "featured": false
  },
  {
    "id": 44,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #10",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/10.jpg",
    "thumb": "assets/photography/tokyo2017/10.jpg",
    "featured": false
  },
  {
    "id": 45,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #11",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/11.jpg",
    "thumb": "assets/photography/tokyo2017/11.jpg",
    "featured": false
  },
  {
    "id": 46,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #12",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/12.jpg",
    "thumb": "assets/photography/tokyo2017/12.jpg",
    "featured": false
  },
  {
    "id": 47,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #13",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/13.jpg",
    "thumb": "assets/photography/tokyo2017/13.jpg",
    "featured": false
  },
  {
    "id": 48,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #14",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/14.jpg",
    "thumb": "assets/photography/tokyo2017/14.jpg",
    "featured": false
  },
  {
    "id": 49,
    "series": "tokyo2017",
    "seriesTitle": "Tokyo (2017)",
    "category": "tokyo",
    "title": "Tokyo \u00b7 #15",
    "location": "Tokyo, Japan",
    "year": "2017",
    "src": "assets/photography/tokyo2017/15.jpg",
    "thumb": "assets/photography/tokyo2017/15.jpg",
    "featured": false
  },
  {
    "id": 50,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #01",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/01.jpg",
    "thumb": "assets/photography/seattle2016/01.jpg",
    "featured": true
  },
  {
    "id": 51,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #02",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/02.jpg",
    "thumb": "assets/photography/seattle2016/02.jpg",
    "featured": false
  },
  {
    "id": 52,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #03",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/03.jpg",
    "thumb": "assets/photography/seattle2016/03.jpg",
    "featured": false
  },
  {
    "id": 53,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #04",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/04.jpg",
    "thumb": "assets/photography/seattle2016/04.jpg",
    "featured": false
  },
  {
    "id": 54,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #05",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/05.jpg",
    "thumb": "assets/photography/seattle2016/05.jpg",
    "featured": false
  },
  {
    "id": 55,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #06",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/06.jpg",
    "thumb": "assets/photography/seattle2016/06.jpg",
    "featured": false
  },
  {
    "id": 56,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #07",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/07.jpg",
    "thumb": "assets/photography/seattle2016/07.jpg",
    "featured": false
  },
  {
    "id": 57,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #08",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/08.jpg",
    "thumb": "assets/photography/seattle2016/08.jpg",
    "featured": false
  },
  {
    "id": 58,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #09",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/09.jpg",
    "thumb": "assets/photography/seattle2016/09.jpg",
    "featured": false
  },
  {
    "id": 59,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #10",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/10.jpg",
    "thumb": "assets/photography/seattle2016/10.jpg",
    "featured": false
  },
  {
    "id": 60,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #11",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/11.jpg",
    "thumb": "assets/photography/seattle2016/11.jpg",
    "featured": false
  },
  {
    "id": 61,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #12",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/12.jpg",
    "thumb": "assets/photography/seattle2016/12.jpg",
    "featured": false
  },
  {
    "id": 62,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #13",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/13.jpg",
    "thumb": "assets/photography/seattle2016/13.jpg",
    "featured": false
  },
  {
    "id": 63,
    "series": "seattle2016",
    "seriesTitle": "Seattle (2016)",
    "category": "seattle",
    "title": "Seattle \u00b7 #14",
    "location": "Seattle, WA",
    "year": "2016",
    "src": "assets/photography/seattle2016/14.jpg",
    "thumb": "assets/photography/seattle2016/14.jpg",
    "featured": false
  },
  {
    "id": 64,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #01",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/01.jpg",
    "thumb": "assets/photography/chicago2016/01.jpg",
    "featured": true
  },
  {
    "id": 65,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #02",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/02.jpg",
    "thumb": "assets/photography/chicago2016/02.jpg",
    "featured": false
  },
  {
    "id": 66,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #03",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/03.jpg",
    "thumb": "assets/photography/chicago2016/03.jpg",
    "featured": false
  },
  {
    "id": 67,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #04",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/04.jpg",
    "thumb": "assets/photography/chicago2016/04.jpg",
    "featured": false
  },
  {
    "id": 68,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #05",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/05.jpg",
    "thumb": "assets/photography/chicago2016/05.jpg",
    "featured": false
  },
  {
    "id": 69,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #06",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/06.jpg",
    "thumb": "assets/photography/chicago2016/06.jpg",
    "featured": false
  },
  {
    "id": 70,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #07",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/07.jpg",
    "thumb": "assets/photography/chicago2016/07.jpg",
    "featured": false
  },
  {
    "id": 71,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #08",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/08.jpg",
    "thumb": "assets/photography/chicago2016/08.jpg",
    "featured": false
  },
  {
    "id": 72,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #09",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/09.jpg",
    "thumb": "assets/photography/chicago2016/09.jpg",
    "featured": false
  },
  {
    "id": 73,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #10",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/10.jpg",
    "thumb": "assets/photography/chicago2016/10.jpg",
    "featured": false
  },
  {
    "id": 74,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #11",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/11.jpg",
    "thumb": "assets/photography/chicago2016/11.jpg",
    "featured": false
  },
  {
    "id": 75,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #12",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/12.jpg",
    "thumb": "assets/photography/chicago2016/12.jpg",
    "featured": false
  },
  {
    "id": 76,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #13",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/13.jpg",
    "thumb": "assets/photography/chicago2016/13.jpg",
    "featured": false
  },
  {
    "id": 77,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #14",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/14.jpg",
    "thumb": "assets/photography/chicago2016/14.jpg",
    "featured": false
  },
  {
    "id": 78,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #15",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/15.jpg",
    "thumb": "assets/photography/chicago2016/15.jpg",
    "featured": false
  },
  {
    "id": 79,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #16",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/16.jpg",
    "thumb": "assets/photography/chicago2016/16.jpg",
    "featured": false
  },
  {
    "id": 80,
    "series": "chicago2016",
    "seriesTitle": "Chicago (2016)",
    "category": "chicago",
    "title": "Chicago \u00b7 #17",
    "location": "Chicago, IL",
    "year": "2016",
    "src": "assets/photography/chicago2016/17.jpg",
    "thumb": "assets/photography/chicago2016/17.jpg",
    "featured": false
  },
  {
    "id": 81,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #01",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/01.jpg",
    "thumb": "assets/photography/debateday2016/01.jpg",
    "featured": true
  },
  {
    "id": 82,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #02",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/02.jpg",
    "thumb": "assets/photography/debateday2016/02.jpg",
    "featured": false
  },
  {
    "id": 83,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #03",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/03.jpg",
    "thumb": "assets/photography/debateday2016/03.jpg",
    "featured": false
  },
  {
    "id": 84,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #04",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/04.jpg",
    "thumb": "assets/photography/debateday2016/04.jpg",
    "featured": false
  },
  {
    "id": 85,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #05",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/05.jpg",
    "thumb": "assets/photography/debateday2016/05.jpg",
    "featured": false
  },
  {
    "id": 86,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #06",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/06.jpg",
    "thumb": "assets/photography/debateday2016/06.jpg",
    "featured": false
  },
  {
    "id": 87,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #07",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/08.jpg",
    "thumb": "assets/photography/debateday2016/08.jpg",
    "featured": false
  },
  {
    "id": 88,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #08",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/09.jpg",
    "thumb": "assets/photography/debateday2016/09.jpg",
    "featured": false
  },
  {
    "id": 89,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #09",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/10.jpg",
    "thumb": "assets/photography/debateday2016/10.jpg",
    "featured": false
  },
  {
    "id": 90,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #10",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/11.jpg",
    "thumb": "assets/photography/debateday2016/11.jpg",
    "featured": false
  },
  {
    "id": 91,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #11",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/12.jpg",
    "thumb": "assets/photography/debateday2016/12.jpg",
    "featured": false
  },
  {
    "id": 92,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #12",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/13.jpg",
    "thumb": "assets/photography/debateday2016/13.jpg",
    "featured": false
  },
  {
    "id": 93,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #13",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/14.jpg",
    "thumb": "assets/photography/debateday2016/14.jpg",
    "featured": false
  },
  {
    "id": 94,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #14",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/15.jpg",
    "thumb": "assets/photography/debateday2016/15.jpg",
    "featured": false
  },
  {
    "id": 95,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #15",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/16.jpg",
    "thumb": "assets/photography/debateday2016/16.jpg",
    "featured": false
  },
  {
    "id": 96,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #16",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/17.jpg",
    "thumb": "assets/photography/debateday2016/17.jpg",
    "featured": false
  },
  {
    "id": 97,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #17",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/18.jpg",
    "thumb": "assets/photography/debateday2016/18.jpg",
    "featured": false
  },
  {
    "id": 98,
    "series": "debateday2016",
    "seriesTitle": "Debate Day at WashU (2016)",
    "category": "washu",
    "title": "Debate Day at WashU \u00b7 #18",
    "location": "St. Louis, MO",
    "year": "2016",
    "src": "assets/photography/debateday2016/19.jpg",
    "thumb": "assets/photography/debateday2016/19.jpg",
    "featured": false
  },
  {
    "id": 99,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #01",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/01.jpg",
    "thumb": "assets/photography/nyc2015/01.jpg",
    "featured": false
  },
  {
    "id": 100,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #02",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/02.jpg",
    "thumb": "assets/photography/nyc2015/02.jpg",
    "featured": false
  },
  {
    "id": 101,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #03",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/03.jpg",
    "thumb": "assets/photography/nyc2015/03.jpg",
    "featured": false
  },
  {
    "id": 102,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #04",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/04.jpg",
    "thumb": "assets/photography/nyc2015/04.jpg",
    "featured": false
  },
  {
    "id": 103,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #05",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/05.jpg",
    "thumb": "assets/photography/nyc2015/05.jpg",
    "featured": false
  },
  {
    "id": 104,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #06",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/06.jpg",
    "thumb": "assets/photography/nyc2015/06.jpg",
    "featured": false
  },
  {
    "id": 105,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #07",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/07.jpg",
    "thumb": "assets/photography/nyc2015/07.jpg",
    "featured": false
  },
  {
    "id": 106,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #08",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/08.jpg",
    "thumb": "assets/photography/nyc2015/08.jpg",
    "featured": false
  },
  {
    "id": 107,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #09",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/09.jpg",
    "thumb": "assets/photography/nyc2015/09.jpg",
    "featured": false
  },
  {
    "id": 108,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #10",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/10.jpg",
    "thumb": "assets/photography/nyc2015/10.jpg",
    "featured": false
  },
  {
    "id": 109,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #11",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/11.jpg",
    "thumb": "assets/photography/nyc2015/11.jpg",
    "featured": false
  },
  {
    "id": 110,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #12",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/12.jpg",
    "thumb": "assets/photography/nyc2015/12.jpg",
    "featured": false
  },
  {
    "id": 111,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #13",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/13.jpg",
    "thumb": "assets/photography/nyc2015/13.jpg",
    "featured": false
  },
  {
    "id": 112,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #14",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/14.jpg",
    "thumb": "assets/photography/nyc2015/14.jpg",
    "featured": false
  },
  {
    "id": 113,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #15",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/15.jpg",
    "thumb": "assets/photography/nyc2015/15.jpg",
    "featured": false
  },
  {
    "id": 114,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #16",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/16.jpg",
    "thumb": "assets/photography/nyc2015/16.jpg",
    "featured": false
  },
  {
    "id": 115,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #17",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/17.jpg",
    "thumb": "assets/photography/nyc2015/17.jpg",
    "featured": false
  },
  {
    "id": 116,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #18",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/18.jpg",
    "thumb": "assets/photography/nyc2015/18.jpg",
    "featured": false
  },
  {
    "id": 117,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #19",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/19.jpg",
    "thumb": "assets/photography/nyc2015/19.jpg",
    "featured": false
  },
  {
    "id": 118,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #20",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/20.jpg",
    "thumb": "assets/photography/nyc2015/20.jpg",
    "featured": false
  },
  {
    "id": 119,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #21",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/21.jpg",
    "thumb": "assets/photography/nyc2015/21.jpg",
    "featured": false
  },
  {
    "id": 120,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #22",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/22.jpg",
    "thumb": "assets/photography/nyc2015/22.jpg",
    "featured": false
  },
  {
    "id": 121,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #23",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/23.jpg",
    "thumb": "assets/photography/nyc2015/23.jpg",
    "featured": false
  },
  {
    "id": 122,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #24",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/24.jpg",
    "thumb": "assets/photography/nyc2015/24.jpg",
    "featured": false
  },
  {
    "id": 123,
    "series": "nyc2015",
    "seriesTitle": "New York City (2015)",
    "category": "nyc",
    "title": "New York City \u00b7 #25",
    "location": "New York, NY",
    "year": "2015",
    "src": "assets/photography/nyc2015/25.jpg",
    "thumb": "assets/photography/nyc2015/25.jpg",
    "featured": false
  }
];
